### ISSUE TITLE
Example API Call for Range returns "Invalid time range type object 'datetime.datetime' has no attribute 'datetime'"

### ISSUE THREAD

**Issue by Tomcariello** [podaac/gibs-imagestat#40] opened 2023-02-27 15:29 UTC
I am trying to execute a date range request but the request returns "Invalid time range type object 'datetime.datetime' has no attribute 'datetime'".

The 'range' request (copied from the docs, updating localhost to the current endpoint):
http://localhost:9000/get_stats?_type=range&timestamp=2016-06-09T00:00:00Z&end_timestamp=2016-06-19T00:00:00Z&steps=5&bins=10&format=json&layer=GHRSST_L4_MUR_Sea_Surface_Temperature&colormap=GHRSST_Sea_Surface_Temperature.xml&bbox=-90,-180,90,180

I am getting the same error response when I try the time series example request.

Please let me know if I am doing something incorrectly. Thank you!

**Comment by frankinspace** [comment] 2023-03-01 18:21
Duplicate of #35

**Comment by frankinspace** [comment] 2023-03-01 23:30
@Tomcariello This has been fixed and deployed.

**Closed as completed by frankinspace** 2023-03-01 23:30 UTC
